### ISSUE TITLE
question

### ISSUE THREAD

**Issue by HDYYZDN** [xuchen-ethz/snarf#2]
在执行 sh ./download_data.sh 出现如下问题：
: not foundta.sh: 2: download_data.sh:
Downloading motion sequences...
: not foundta.sh: 4: download_data.sh:
--2021-11-03 01:26:23--  https://scanimate.is.tue.mpg.de/media/upload/demo_data/aist_demo_seq.zip%0D
Resolving scanimate.is.tue.mpg.de (scanimate.is.tue.mpg.de)... 192.124.27.142
Connecting to scanimate.is.tue.mpg.de (scanimate.is.tue.mpg.de)|192.124.27.142|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-03 01:26:24 ERROR 404: Not Found.

unzip:  cannot find or open aist_demo_seq.zip, aist_demo_seq.zip.zip or aist_demo_seq.zip.ZIP.
rm: cannot remove 'aist_demo_seq.zip'$'\r': No such file or directory
mv: cannot stat './data/gLO_sBM_cAll_d14_mLO1_ch05': No such file or directory
: not foundta.sh: 9: download_data.sh:
Done!
: not foundta.sh: 11: download_data.sh:
: not foundta.sh: 12: download_data.sh:
mkdir: cannot create directory ‘outputs\r’: File exists
: not foundta.sh: 14: download_data.sh:
Downloading pretrained models ...
--2021-11-03 01:26:24--  https://dataset.ait.ethz.ch/downloads/fOUiBuCXJy/pretrained_models.zip%0D
Resolving dataset.ait.ethz.ch (dataset.ait.ethz.ch)... 129.132.114.75
Connecting to dataset.ait.ethz.ch (dataset.ait.ethz.ch)|129.132.114.75|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-03 01:26:25 ERROR 404: Not Found.

unzip:  cannot find or open pretrained_models.zip, pretrained_models.zip.zip or pretrained_models.zip.ZIP.
mv: cannot stat 'outputs/pretrained_models/*': No such file or directory
'm: invalid option -- '
Try 'rm --help' for more information.
rm: cannot remove 'pretrained_models.zip'$'\r': No such file or directory

**Comment by xuchen-ethz** [comment]
Hi, it seems that the download link does not work for you for some reason. I just tested the link again and they work fine on my side. So it could be some network issue on your side.
