### ISSUE TITLE
Training for CAPE dataset

### ISSUE THREAD

**Issue by iwanao731** [xuchen-ethz/snarf#4]
Hi
I would like to train CAPE dataset by myself.
By following the guidance, I put CAPE dataset under the data directory as shown below.
> data/CAPE/03375
> data/CAPE/cape_release

And I run the command for training.
> python train.py datamodule=cape subject=3375 datamodule.clothing='blazerlong' +experiments=cape  

Then the error was shown below.
> ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

Do you have any idea to solve it?
Thanks

**Comment by xuchen-ethz** [comment]
The CAPE dataloder looks for data in data/CAPE/03375/<sequence_name>/<sequence_name>.<id>.npz. Could you check if the files are indeed there?

**Comment by xuchen-ethz** [comment]
this issue seems no longer active so I am closing it. Feel free to re-open it if the problem remains
