### ISSUE TITLE
How to generate the 2D stick dataset? 

### ISSUE THREAD

**Issue by yashkant** [xuchen-ethz/snarf#7]
Hi, thanks for releasing the code! 

I just have a simple question -- how did you guys generate data for the 2D stick toy experiment [Figure 4]? Could you share a piece of code/pointer for doing this? 

Appreciate your help! 

![image](https://user-images.githubusercontent.com/17530895/164764829-397db7d1-bc2f-4cd8-b271-8774455dbf16.png)

**Comment by xuchen-ethz** [comment]
Hi @yashkant,
here is the code for generating the 2D stick dataset (not cleaned yet): [gt_shape.txt](https://github.com/xuchen-ethz/snarf/files/8550401/gt_shape.txt).  Let me know if there is any question.

**Comment by yashkant** [comment]
Thank you so much, @xuchen-ethz, I will try this out!

**Comment by JoeyWen99** [comment]
hi! @xuchen-ethz , how to train the 2D datasets with the code gt_shape you just released and visualize the result ?
